apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: enum-backend
  name: enum-backend
  namespace: enum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      tier: enum-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
        tier: enum-backend
    spec:
      containers:
      - image: 192.168.8.240:31320/enum_back:v1.4
        imagePullPolicy: IfNotPresent
        name: enum-backend
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
      dnsConfig:
        nameservers:
        - 8.8.8.8
      dnsPolicy: None
      restartPolicy: Always
