apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-enum-server
  name: apche-enum-service
  namespace: enum
spec:
  ipFamilies:
  - IPv4
  ports:
  - name: http
    nodePort: 32143
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32144
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: apache-enum-server
  sessionAffinity: None
  type: NodePort
